select
*
from
(SELECT 
  'NF FATURADAS' AS TIPO,
  tnota_fiscal.DT_EMISSAO AS Data, 
  cast(TNOTA_FISCAL.NUMERO as VARCHAR) AS NF, 
  TNOTA_FISCAL.RAZAO_SOCIAL AS CLIENTE,    
  TNOTA_FISCAL.CGC_CPF AS CNPJ,       
  TNOTA_FISCAL_ITEM.CFOP,   
  CASE TNOTA_FISCAL.NFE_COD_STATUS                             
  WHEN '101' THEN 'CANCELADA'                                              
  WHEN '102' THEN 'INUTILIZADA' 
  WHEN ''  THEN 'NÃO ENVIADA'
  WHEN '100' THEN 'AUTORIZADA'
  WHEN '150' THEN 'AUTORIZADO O USO DA NF-E, AUTORIZAÇÃO FORA DE PRAZO'                   
  END AS Status,  
  CASE                                                                                   
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND (TNOTA_FISCAL_ITEM.CFOP LIKE '3%' or TNOTA_FISCAL_ITEM.CFOP LIKE '7%')  THEN
  (coalesce(SUM(tnota_fiscal_item.vl_total),0)+
coalesce(SUM(tnota_fiscal_item.vl_icms),0)+
coalesce(SUM(tnota_fiscal_item.vl_ipi),0)+
coalesce(SUM(tnota_fiscal_item.vpis_q09),0)+
coalesce(SUM(tnota_fiscal_item.vcofins_s11),0)+
coalesce(SUM(tnota_fiscal_item.vl_outras_despesas),0)+
coalesce(SUM(tnota_fiscal_item.vii_p04),0))

    WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_ITEM.CFOP not LIKE '3%'  THEN 
  SUM(TNOTA_FISCAL_ITEM.VL_TOTAL)+  coalesce(SUM(tnota_fiscal_item.vl_ipi),0)
  ELSE 0 END AS VL_NOTA,
                                                                              

  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO = 1 THEN
  SUM(TNOTA_FISCAL_ITEM.VL_TOTAL) +  coalesce(SUM(tnota_fiscal_item.vl_ipi),0) + coalesce(SUM(tnota_fiscal_item.vl_outras_despesas),0)
  ELSE 0 END  AS VL_FATURADO,  
  
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VL_ICMS) 
  ELSE 0 END  AS ICMS, 
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN   
  SUM(TNOTA_FISCAL_ITEM.VPIS_Q09) 
  ELSE 0 END  AS PIS,
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VCOFINS_S11) 
  ELSE 0 END  AS Cofins,      
       
  TORCAMENTO.CLASSIFICACAO AS Segmento,
  CASE TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO
  WHEN 1  THEN 'SIM'
  WHEN 0 THEN 'NAO'
  END AS NF_FATURAMENTO,
  '' as NF_REFERENCIADA,      
  CASE TNOTA_FISCAL.CLI_FOR 
  WHEN 1 THEN 'FORNECEDOR'
  WHEN 0 THEN 'CLIENTE' END AS TP_NF ,
  0 as ISS,
'' AS ORC_DEV,
sum(tnota_fiscal_item.vl_frete) as vl_frete,
tnota_fiscal.frete_por_conta,

 CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VL_IPI) 
  ELSE 0 END  AS IPI,
  convert_from(obs_nota, 'WIN1252') AS obs_nota,
  coalesce(sum(tnota_fiscal_item.vl_outras_despesas),0) as OUTRAS_DESPESAS

FROM
  TNOTA_FISCAL                                
  INNER JOIN TNOTA_FISCAL_ITEM ON (TNOTA_FISCAL.COD_EMPRESA = TNOTA_FISCAL_ITEM.COD_EMPRESA)
  AND (TNOTA_FISCAL.MODELO = TNOTA_FISCAL_ITEM.MODELO)
  AND (TNOTA_FISCAL.SERIE = TNOTA_FISCAL_ITEM.SERIE)
  AND (TNOTA_FISCAL.SUB_SERIE = TNOTA_FISCAL_ITEM.SUB_SERIE)
  AND (TNOTA_FISCAL.NUMERO = TNOTA_FISCAL_ITEM.NUMERO_NF)
  FULL OUTER JOIN TORCAMENTO_ITENS ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TORCAMENTO_ITENS.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.COD_ORCAMENTO = TORCAMENTO_ITENS.COD_ORCAMENTO)
  AND (TNOTA_FISCAL_ITEM.COD_PRODUTO = TORCAMENTO_ITENS.COD_PRODUTO)
  AND (torcamento_itens.guid_linha = tnota_fiscal_item.guid_orcamento)
  FULL OUTER JOIN TORCAMENTO ON (TORCAMENTO_ITENS.COD_EMPRESA = TORCAMENTO.COD_EMPRESA)
  AND (TORCAMENTO_ITENS.COD_ORCAMENTO = TORCAMENTO.CODIGO)
    INNER JOIN TPRODUTO ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TPRODUTO.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.COD_PRODUTO = TPRODUTO.CODIGO)                                        
WHERE       
  TNOTA_FISCAL.NFE_FINALIDADE <> '4'   
 AND TPRODUTO.COD_FAMILIA <> 30
   --and tnota_fiscal.numero   = 9567
 and TNOTA_FISCAL.NFE_COD_STATUS NOT IN ('102','101','105')

GROUP BY
  TNOTA_FISCAL.DT_EMISSAO,
  TNOTA_FISCAL.NUMERO,                                       
  TNOTA_FISCAL.RAZAO_SOCIAL,                                                  
  TNOTA_FISCAL.CGC_CPF,                              
  TNOTA_FISCAL_ITEM.CFOP,                           
  TNOTA_FISCAL.NFE_COD_STATUS,                            
  TORCAMENTO.CLASSIFICACAO,
  TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO,
  TNOTA_FISCAL.CLI_FOR,
  tnota_fiscal.frete_por_conta,
  TNOTA_FISCAL.obs_nota
                            
  
  UNION    
  
  SELECT 
  'SUCATA' AS TIPO, 
  TNOTA_FISCAL.DT_EMISSAO,  
  cast(TNOTA_FISCAL.NUMERO as VARCHAR) AS NF,         
  TNOTA_FISCAL.RAZAO_SOCIAL,                  
  TNOTA_FISCAL.CGC_CPF AS CNPJ,      
  TNOTA_FISCAL_ITEM.CFOP,     
  CASE TNOTA_FISCAL.NFE_COD_STATUS                        
  WHEN '101' THEN 'CANCELADA'         
  WHEN '102' THEN 'INUTILIZADA' 
  WHEN ''  THEN 'NÃO ENVIADA'     
  WHEN '100' THEN 'AUTORIZADA'
  WHEN '150' THEN 'AUTORIZADO O USO DA NF-E, AUTORIZAÇÃO FORA DE PRAZO'                   
  END AS STATUS,                                              
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150')  THEN 
  SUM(TNOTA_FISCAL_ITEM.VL_TOTAL)+coalesce(SUM(tnota_fiscal_item.vl_ipi),0)
  ELSE 0 END  AS VL_NOTA,             
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO = 1 THEN
  SUM(TNOTA_FISCAL_ITEM.VL_TOTAL)                            
  ELSE 0 END  AS VL_FATURADO,    
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VL_ICMS)                       
  ELSE 0 END  AS ICMS,         
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN   
  SUM(TNOTA_FISCAL_ITEM.VPIS_Q09) 
  ELSE 0 END  AS PIS,
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VCOFINS_S11) 
  ELSE 0 END  AS COFINS,             
  'SUCATA' AS SEGMENTO,          
  CASE TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO
  WHEN 1  THEN 'SIM'
  WHEN 0 THEN 'NAO'
  END AS NF_FATURAMENTO,
  ' ' AS NF_REFERENCIADA,      
  CASE TNOTA_FISCAL.CLI_FOR 
  WHEN 1 THEN 'FORNECEDOR'
  WHEN 0 THEN 'CLIENTE' END AS TP_NF,
  0,
'',
sum(tnota_fiscal_item.vl_frete),
tnota_fiscal.frete_por_conta,
 CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VL_IPI) 
  ELSE 0 END  AS IPI,
  convert_from(obs_nota, 'WIN1252') AS obs_text,
  coalesce(sum(tnota_fiscal_item.vl_outras_despesas),0)
FROM
  TNOTA_FISCAL
  INNER JOIN TNOTA_FISCAL_ITEM ON (TNOTA_FISCAL.COD_EMPRESA = TNOTA_FISCAL_ITEM.COD_EMPRESA)
  AND (TNOTA_FISCAL.MODELO = TNOTA_FISCAL_ITEM.MODELO)
  AND (TNOTA_FISCAL.SERIE = TNOTA_FISCAL_ITEM.SERIE)
  AND (TNOTA_FISCAL.SUB_SERIE = TNOTA_FISCAL_ITEM.SUB_SERIE)
  AND (TNOTA_FISCAL.NUMERO = TNOTA_FISCAL_ITEM.NUMERO_NF)
  FULL OUTER JOIN TORCAMENTO_ITENS ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TORCAMENTO_ITENS.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.COD_ORCAMENTO = TORCAMENTO_ITENS.COD_ORCAMENTO)
  AND (TNOTA_FISCAL_ITEM.COD_PRODUTO = TORCAMENTO_ITENS.COD_PRODUTO)
  AND (torcamento_itens.guid_linha = tnota_fiscal_item.guid_orcamento)
  FULL OUTER JOIN TORCAMENTO ON (TORCAMENTO_ITENS.COD_EMPRESA = TORCAMENTO.COD_EMPRESA)
  AND (TORCAMENTO_ITENS.COD_ORCAMENTO = TORCAMENTO.CODIGO)
  INNER JOIN TPRODUTO ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TPRODUTO.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.COD_PRODUTO = TPRODUTO.CODIGO)
                                          
WHERE       
  TNOTA_FISCAL.NFE_FINALIDADE <> '4'               
  AND TPRODUTO.COD_FAMILIA = 30   
  and TNOTA_FISCAL.NFE_COD_STATUS NOT IN ('102','101','105')


GROUP BY
  TNOTA_FISCAL.DT_EMISSAO,
  TNOTA_FISCAL.NUMERO,                                       
  TNOTA_FISCAL.RAZAO_SOCIAL,                                                  
  TNOTA_FISCAL.CGC_CPF,                              
  TNOTA_FISCAL_ITEM.CFOP,                           
  TNOTA_FISCAL.NFE_COD_STATUS,                            
  TORCAMENTO.CLASSIFICACAO,
  TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO,
  TNOTA_FISCAL.CLI_FOR,
  tnota_fiscal.frete_por_conta,
  TNOTA_FISCAL.obs_nota
  
UNION                                                                   
                                                  
   -- EMISSÃO DE NF DEDEVOLUÇÃO
                                                 
SELECT                                                  
  'EMISSAO DEVOLUCAO' AS TIPO,
  TNOTA_FISCAL.DT_EMISSAO,
  cast(TNOTA_FISCAL.NUMERO as VARCHAR),
  TNOTA_FISCAL.RAZAO_SOCIAL,
  TNOTA_FISCAL.CGC_CPF,
  TNOTA_FISCAL_ITEM.CFOP,
  CASE TNOTA_FISCAL.NFE_COD_STATUS                        
  WHEN '101' THEN 'CANCELADA' 
  WHEN '102' THEN 'INUTILIZADA' 
  WHEN ''  THEN 'NÃO ENVIADA'                               
  WHEN '100' THEN 'AUTORIZADA'
  WHEN '150' THEN 'AUTORIZADO O USO DA NF-E, AUTORIZAÇÃO FORA DE PRAZO'                   
  END AS STATUS,
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150')  THEN 
  (SUM(TNOTA_FISCAL_ITEM.VL_TOTAL)+coalesce(SUM(tnota_fiscal_item.vl_ipi),0))
  ELSE 0 END  AS VL_NOTA,             
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO = 1 THEN
  SUM(TNOTA_FISCAL_ITEM.VL_TOTAL) 
  ELSE 0 END  AS VL_FATURADO, 
    CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VL_ICMS)                       
  ELSE 0 END  AS ICMS,         
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN   
  SUM(TNOTA_FISCAL_ITEM.VPIS_Q09) 
  ELSE 0 END  AS PIS,
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VCOFINS_S11) 
  ELSE 0 END  AS COFINS,
  TORCAMENTO.CLASSIFICACAO,
  CASE TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO
  WHEN 1  THEN 'SIM'
  WHEN 0 THEN 'NAO'
  END AS NF_FATURAMENTO,
  casT(TNOTA_FISCAL_NFREF.NFREF_NUMERO_NF as VARCHAR),      
  CASE TNOTA_FISCAL.CLI_FOR 
  WHEN 1 THEN 'FORNECEDOR'
  WHEN 0 THEN 'CLIENTE' END AS TP_NF,
  0,
  TNOTA_FISCAL_ITEM.N_OS_CLIENTE,
  sum(tnota_fiscal_item.vl_frete),
  tnota_fiscal.frete_por_conta,
 CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VL_IPI) 
  ELSE 0 END  AS IPI,
  convert_from(obs_nota, 'WIN1252') AS obs_text,
  coalesce(sum(tnota_fiscal_item.vl_outras_despesas),0)
FROM
  TNOTA_FISCAL_ITEM
  INNER JOIN TNOTA_FISCAL ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TNOTA_FISCAL.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.MODELO = TNOTA_FISCAL.MODELO)
  AND (TNOTA_FISCAL_ITEM.SERIE = TNOTA_FISCAL.SERIE)          
  AND (TNOTA_FISCAL_ITEM.SUB_SERIE = TNOTA_FISCAL.SUB_SERIE)
  AND (TNOTA_FISCAL_ITEM.NUMERO_NF = TNOTA_FISCAL.NUMERO)
  INNER JOIN TNOTA_FISCAL_NFREF ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TNOTA_FISCAL_NFREF.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.MODELO = TNOTA_FISCAL_NFREF.MODELO)
  AND (TNOTA_FISCAL_ITEM.SERIE = TNOTA_FISCAL_NFREF.SERIE)
  AND (TNOTA_FISCAL_ITEM.SUB_SERIE = TNOTA_FISCAL_NFREF.SUB_SERIE)
  AND (TNOTA_FISCAL_ITEM.NUMERO_NF = TNOTA_FISCAL_NFREF.NUMERO_NF)
  LEFT JOIN TNOTA_FISCAL_ITEM TNOTA_FISCAL_ITEM1 ON (TNOTA_FISCAL_NFREF.COD_EMPRESA = TNOTA_FISCAL_ITEM1.COD_EMPRESA)
  AND (TNOTA_FISCAL_NFREF.NFREF_MODELO = TNOTA_FISCAL_ITEM1.MODELO)
  AND (TNOTA_FISCAL_NFREF.NFREF_SERIE = TNOTA_FISCAL_ITEM1.SERIE)
  AND (TNOTA_FISCAL_NFREF.NFREF_SUB_SERIE = TNOTA_FISCAL_ITEM1.SUB_SERIE)
  AND (TNOTA_FISCAL_NFREF.NFREF_NUMERO_NF = TNOTA_FISCAL_ITEM1.NUMERO_NF)
  AND (TNOTA_FISCAL_ITEM.COD_PRODUTO = TNOTA_FISCAL_ITEM1.COD_PRODUTO)
 LEFT JOIN TORCAMENTO_ITENS ON (TNOTA_FISCAL_ITEM1.COD_ORCAMENTO = TORCAMENTO_ITENS.COD_ORCAMENTO)
  AND (TNOTA_FISCAL_ITEM1.COD_EMPRESA = TORCAMENTO_ITENS.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM1.COD_PRODUTO = TORCAMENTO_ITENS.COD_PRODUTO)
  AND (torcamento_itens.guid_linha = tnota_fiscal_item1.guid_orcamento)
  LEFT JOIN TORCAMENTO ON (TORCAMENTO_ITENS.COD_EMPRESA = TORCAMENTO.COD_EMPRESA)
  AND (TORCAMENTO_ITENS.COD_ORCAMENTO = TORCAMENTO.CODIGO)
                                    

                                                                           
WHERE
    
 TNOTA_FISCAL.NFE_FINALIDADE = '4'  
 and TNOTA_FISCAL.NFE_COD_STATUS NOT IN ('102','101','105')  
 --and tnota_fiscal.numero = 10829
 --and TNOTA_FISCAL.DT_EMISSAO >= '20260101' 
                           
 GROUP BY                           
                                     
   TNOTA_FISCAL.NUMERO,                                      
  TNOTA_FISCAL.DT_EMISSAO,                                  
  TNOTA_FISCAL.RAZAO_SOCIAL,
  TNOTA_FISCAL.CGC_CPF,                                   
  TNOTA_FISCAL_ITEM.CFOP,                     
  TNOTA_FISCAL.NFE_COD_STATUS,
  TNOTA_FISCAL_NFREF.NFREF_NUMERO_NF,
  TORCAMENTO.CLASSIFICACAO,
  TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO,
  TNOTA_FISCAL.CLI_FOR,
  TNOTA_FISCAL_ITEM.N_OS_CLIENTE,
    tnota_fiscal.frete_por_conta,
    TNOTA_FISCAL.obs_nota

                                           
  
         UNION
         
       -- ENTRADA DE NF DE DEVOLUÇÃO
                                                              
SELECT
  'ENTRADA' AS TIPO,
  TCOMPRAS.DT_LANCAMENTO, 
  cast(TCOMPRAS.N_NF as VARCHAR),
  TCLIENTE.RAZAO_SOCIAL,
  TCLIENTE.RG_CGC,
  TCOM_AUX.CFOP,                  
  'AUTORIZADA' AS STATUS,
  SUM(TCOM_AUX.TOTAL) AS VL_TOTAL,
    SUM(TCOM_AUX.TOTAL) AS VL_FATURAMETO,
  SUM(TCOM_AUX.VL_ICMS) AS VL_ICMS,
  SUM(TCOM_AUX.VPIS_Q09) AS VL_PIS,
  SUM(TCOM_AUX.VCOFINS_S11) AS VL_COFINS,
  TORCAMENTO.CLASSIFICACAO,
  'SIM' AS NF_FATURAMENTO,
   TNOTA_FISCAL_ENTRAREF.ENTRAREF_NUMERO_NF,     
  CASE TCOMPRAS.CLI_FOR 
  WHEN 1 THEN 'FORNECEDOR'
  WHEN 0 THEN 'CLIENTE' END AS TP_NF ,
  0,
  TCOM_AUX.obs as ORC_DEV,
  0,
  0,
sum(TCOM_AUX.VL_IPI),
'',
NULL
FROM
  TNOTA_FISCAL_ENTRAREF
  LEFT JOIN TCOM_AUX ON (TNOTA_FISCAL_ENTRAREF.COD_EMPRESA = TCOM_AUX.COD_EMPRESA)
  AND (TNOTA_FISCAL_ENTRAREF.COD_COMPRA = TCOM_AUX.REALCIONA_AUTO)
  LEFT JOIN TCOMPRAS ON (TCOM_AUX.COD_EMPRESA = TCOMPRAS.COD_EMPRESA)
  AND (TCOM_AUX.REALCIONA_AUTO = TCOMPRAS.CODIGO)
  LEFT JOIN TNOTA_FISCAL ON (TNOTA_FISCAL_ENTRAREF.COD_EMPRESA = TNOTA_FISCAL.COD_EMPRESA)
  AND (TNOTA_FISCAL_ENTRAREF.ENTRAREF_CHAVE_NF = TNOTA_FISCAL.CHV_NFE)
  LEFT JOIN TNOTA_FISCAL_ITEM ON (TNOTA_FISCAL.COD_EMPRESA = TNOTA_FISCAL_ITEM.COD_EMPRESA)
  AND (TNOTA_FISCAL.MODELO = TNOTA_FISCAL_ITEM.MODELO)
  AND (TNOTA_FISCAL.SERIE = TNOTA_FISCAL_ITEM.SERIE)
  AND (TNOTA_FISCAL.SUB_SERIE = TNOTA_FISCAL_ITEM.SUB_SERIE)                 
  AND (TNOTA_FISCAL.NUMERO = TNOTA_FISCAL_ITEM.NUMERO_NF)                                    
  AND (TCOM_AUX.COD_PRODUTO = TNOTA_FISCAL_ITEM.COD_PRODUTO)
  LEFT JOIN TORCAMENTO_ITENS ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TORCAMENTO_ITENS.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.COD_ORCAMENTO = TORCAMENTO_ITENS.COD_ORCAMENTO)
  AND (TNOTA_FISCAL_ITEM.COD_PRODUTO = TORCAMENTO_ITENS.COD_PRODUTO)
AND (torcamento_itens.guid_linha = tnota_fiscal_item.guid_orcamento)
  LEFT JOIN TORCAMENTO ON (TORCAMENTO_ITENS.COD_EMPRESA = TORCAMENTO.COD_EMPRESA)
  AND (TORCAMENTO_ITENS.COD_ORCAMENTO = TORCAMENTO.CODIGO)
  INNER JOIN TCLIENTE ON (TCOMPRAS.COD_EMPRESA = TCLIENTE.COD_EMPRESA)
  AND (TCOMPRAS.COD_CLIENTE = TCLIENTE.CODIGO) 
  where tcom_aux.cfop not like '%949'
  --where tcompras.CODIGO = 13918
  GROUP BY
  TCOMPRAS.N_NF,                                             
  TCOMPRAS.DT_LANCAMENTO,
  TCLIENTE.RAZAO_SOCIAL,                              
  TCLIENTE.RG_CGC,
  TCOM_AUX.CFOP, 
  TORCAMENTO.CLASSIFICACAO,
  TNOTA_FISCAL_ENTRAREF.ENTRAREF_NUMERO_NF,
  TCOMPRAS.CLI_FOR,
  TCOM_AUX.obs

  
  union
  
  SELECT 
  'NF SERVICO' AS TIPO,
  tnota_fiscal.DT_EMISSAO AS Data, 
  cast(TNOTA_FISCAL.NUMERO as VARCHAR) AS NF, 
  TNOTA_FISCAL.RAZAO_SOCIAL AS CLIENTE,    
  TNOTA_FISCAL.CGC_CPF AS CNPJ,       
       tnota_fiscal_servico.CFOP,   
  CASE TNOTA_FISCAL.NFE_COD_STATUS                             
  WHEN '101' THEN 'CANCELADA'                                              
  WHEN '102' THEN 'INUTILIZADA' 
  WHEN ''  THEN 'NÃO ENVIADA'
  WHEN '100' THEN 'AUTORIZADA'
  WHEN '150' THEN 'AUTORIZADO O USO DA NF-E, AUTORIZAÇÃO FORA DE PRAZO'                   
  END AS Status,  
  CASE                                                                                   
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  SUM(tnota_fiscal_servico.VL_TOTAL)  
  else 0
   end AS VL_NOTA,
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_SERVICO.GERAR_FATURAMENTO = 1 THEN
  SUM(tnota_fiscal_servico.VL_TOTAL) 
  ELSE 0 END  AS VL_FATURADO,
  0 as ICMS,
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN   
  SUM(TNOTA_FISCAL_SERVICO.VPIS_Q09) 
  ELSE 0 END  AS PIS,
    CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_SERVICO.vcofins_s11) 
  ELSE 0 END  AS Cofins,
  TORCAMENTO.CLASSIFICACAO AS Segmento,
  CASE TNOTA_FISCAL_SERVICO.GERAR_FATURAMENTO
  WHEN 1  THEN 'SIM'
  WHEN 0 THEN 'NAO'
  END AS NF_FATURAMENTO,
  '' as NF_REFERENCIADA,      
  CASE TNOTA_FISCAL.CLI_FOR 
  WHEN 1 THEN 'FORNECEDOR'
  WHEN 0 THEN 'CLIENTE' END AS TP_NF,
    CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_SERVICO.GERAR_FATURAMENTO = 1 THEN
  SUM(TNOTA_FISCAL.vl_iss) 
  ELSE 0 END   as ISS,
'',
0,
tnota_fiscal.frete_por_conta,
0,
convert_from(obs_nota, 'WIN1252') AS obs_text,
NULL
FROM
  TNOTA_FISCAL                                
  INNER JOIN      tnota_fiscal_servico ON (TNOTA_FISCAL.COD_EMPRESA =      tnota_fiscal_servico.COD_EMPRESA)
  AND (TNOTA_FISCAL.MODELO =      tnota_fiscal_servico.MODELO)
  AND (TNOTA_FISCAL.SERIE =      tnota_fiscal_servico.SERIE)
  AND (TNOTA_FISCAL.SUB_SERIE =      tnota_fiscal_servico.SUB_SERIE)
  AND (TNOTA_FISCAL.NUMERO =      tnota_fiscal_servico.NUMERO_NF)
  FULL OUTER JOIN TORCAMENTO_ITENS ON (     tnota_fiscal_servico.COD_EMPRESA = TORCAMENTO_ITENS.COD_EMPRESA)
  AND (     tnota_fiscal_servico.COD_ORCAMENTO = TORCAMENTO_ITENS.COD_ORCAMENTO)
  AND (torcamento_itens.guid_linha =      tnota_fiscal_servico.guid_orcamento)
  FULL OUTER JOIN TORCAMENTO ON (TORCAMENTO_ITENS.COD_EMPRESA = TORCAMENTO.COD_EMPRESA)
  AND (TORCAMENTO_ITENS.COD_ORCAMENTO = TORCAMENTO.CODIGO)
                                      
WHERE       
  TNOTA_FISCAL.NFE_FINALIDADE <> '4'   
  and TNOTA_FISCAL.COD_EMPRESA = 1
  and TNOTA_FISCAL.DT_EMISSAO >= '20250101'
 --AND TPRODUTO.COD_FAMILIA <> 30
   -- and tnota_fiscal.numero   = 9277
  and TNOTA_FISCAL.NFE_COD_STATUS NOT IN ('102','101','105')

GROUP BY
  TNOTA_FISCAL.DT_EMISSAO,
  TNOTA_FISCAL.NUMERO,                                       
  TNOTA_FISCAL.RAZAO_SOCIAL,                                                  
  TNOTA_FISCAL.CGC_CPF,                              
       tnota_fiscal_servico.CFOP,                           
  TNOTA_FISCAL.NFE_COD_STATUS,                            
  TORCAMENTO.CLASSIFICACAO,
       tnota_fiscal_servico.GERAR_FATURAMENTO,
  TNOTA_FISCAL.CLI_FOR,
  TNOTA_FISCAL.vl_iss,
  tnota_fiscal.frete_por_conta,
  TNOTA_FISCAL.obs_nota
  
  union all
  
  SELECT
'NF INUT/CANC' AS TIPO,
  tnota_fiscal.DT_EMISSAO AS Data, 
  cast(TNOTA_FISCAL.NUMERO as VARCHAR) AS NF, 
  TNOTA_FISCAL.RAZAO_SOCIAL AS CLIENTE,    
  TNOTA_FISCAL.CGC_CPF AS CNPJ,       
  TNOTA_FISCAL_ITEM.CFOP,   
  CASE TNOTA_FISCAL.NFE_COD_STATUS                             
  WHEN '101' THEN 'CANCELADA'                                              
  WHEN '102' THEN 'INUTILIZADA' 
  WHEN ''  THEN 'NÃO ENVIADA'
  WHEN '100' THEN 'AUTORIZADA'
  WHEN '150' THEN 'AUTORIZADO O USO DA NF-E, AUTORIZAÇÃO FORA DE PRAZO'                   
  END AS Status,  
  CASE                                                                                   
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_ITEM.CFOP LIKE '3%'  THEN
  (coalesce(SUM(tnota_fiscal_item.vl_total),0)+
coalesce(SUM(tnota_fiscal_item.vl_icms),0)+
coalesce(SUM(tnota_fiscal_item.vl_ipi),0)+
coalesce(SUM(tnota_fiscal_item.vpis_q09),0)+
coalesce(SUM(tnota_fiscal_item.vcofins_s11),0)+
coalesce(SUM(tnota_fiscal_item.vl_outras_despesas),0)+
coalesce(SUM(tnota_fiscal_item.vii_p04),0)) 
    WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_ITEM.CFOP not LIKE '3%'  THEN 
  SUM(TNOTA_FISCAL_ITEM.VL_TOTAL)+  coalesce(SUM(tnota_fiscal_item.vl_ipi),0)
  ELSE 0 END AS VL_NOTA,
                                                                              

  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') AND TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO = 1 THEN
  SUM(TNOTA_FISCAL_ITEM.VL_TOTAL) +  coalesce(SUM(tnota_fiscal_item.vl_ipi),0)
  ELSE 0 END  AS VL_FATURADO,  
  
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VL_ICMS) 
  ELSE 0 END  AS ICMS, 
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN   
  SUM(TNOTA_FISCAL_ITEM.VPIS_Q09) 
  ELSE 0 END  AS PIS,
  CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VCOFINS_S11) 
  ELSE 0 END  AS Cofins,      
       
  TORCAMENTO.CLASSIFICACAO AS Segmento,
  CASE TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO
  WHEN 1  THEN 'SIM'
  WHEN 0 THEN 'NAO'
  END AS NF_FATURAMENTO,
  '' as NF_REFERENCIADA,      
  CASE TNOTA_FISCAL.CLI_FOR 
  WHEN 1 THEN 'FORNECEDOR'
  WHEN 0 THEN 'CLIENTE' END AS TP_NF ,
  0 as ISS,
'' AS ORC_DEV,
sum(tnota_fiscal_item.vl_frete) as vl_frete,
tnota_fiscal.frete_por_conta,

 CASE 
  WHEN TNOTA_FISCAL.NFE_COD_STATUS IN ('100', '150') THEN  
  SUM(TNOTA_FISCAL_ITEM.VL_IPI) 
  ELSE 0 END  AS IPI,
  convert_from(obs_nota, 'WIN1252') AS obs_nota,
  NULL

FROM
  TNOTA_FISCAL                                
  full OUTER JOIN TNOTA_FISCAL_ITEM ON (TNOTA_FISCAL.COD_EMPRESA = TNOTA_FISCAL_ITEM.COD_EMPRESA)
  AND (TNOTA_FISCAL.MODELO = TNOTA_FISCAL_ITEM.MODELO)
  AND (TNOTA_FISCAL.SERIE = TNOTA_FISCAL_ITEM.SERIE)
  AND (TNOTA_FISCAL.SUB_SERIE = TNOTA_FISCAL_ITEM.SUB_SERIE)
  AND (TNOTA_FISCAL.NUMERO = TNOTA_FISCAL_ITEM.NUMERO_NF)
  FULL OUTER JOIN TORCAMENTO_ITENS ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TORCAMENTO_ITENS.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.COD_ORCAMENTO = TORCAMENTO_ITENS.COD_ORCAMENTO)
  AND (TNOTA_FISCAL_ITEM.COD_PRODUTO = TORCAMENTO_ITENS.COD_PRODUTO)
  AND (torcamento_itens.guid_linha = tnota_fiscal_item.guid_orcamento)
  FULL OUTER JOIN TORCAMENTO ON (TORCAMENTO_ITENS.COD_EMPRESA = TORCAMENTO.COD_EMPRESA)
  AND (TORCAMENTO_ITENS.COD_ORCAMENTO = TORCAMENTO.CODIGO)
  full OUTER JOIN TPRODUTO ON (TNOTA_FISCAL_ITEM.COD_EMPRESA = TPRODUTO.COD_EMPRESA)
  AND (TNOTA_FISCAL_ITEM.COD_PRODUTO = TPRODUTO.CODIGO)                                        
WHERE       
  TNOTA_FISCAL.NFE_FINALIDADE <> '4'   
 --AND TPRODUTO.COD_FAMILIA <> 30
  and TNOTA_FISCAL.NFE_COD_STATUS IN ('102','101','105')
   --and tnota_fiscal.numero   = 10701

GROUP BY
  TNOTA_FISCAL.DT_EMISSAO,
  TNOTA_FISCAL.NUMERO,                                       
  TNOTA_FISCAL.RAZAO_SOCIAL,                                                  
  TNOTA_FISCAL.CGC_CPF,                              
  TNOTA_FISCAL_ITEM.CFOP,                           
  TNOTA_FISCAL.NFE_COD_STATUS,                            
  TORCAMENTO.CLASSIFICACAO,
  TNOTA_FISCAL_ITEM.GERAR_FATURAMENTO,
  TNOTA_FISCAL.CLI_FOR,
  tnota_fiscal.frete_por_conta,
  TNOTA_FISCAL.obs_nota
  
  ) as teste
WHERE EXTRACT(YEAR FROM teste.data) > 2023
  AND COALESCE(teste.nf, '') NOT LIKE '%11825%';
